spring:
  r2dbc:
    url: r2dbc:postgresql://${DATABASE_URL_UNJ?:sonifoy-db:5432/user_db}
    username: ${PGUSER:sonifoy_user}
    password: ${PGPASSWORD:sonifoy_password}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka/}
  instance:
    hostname: ${RAILWAY_PRIVATE_DOMAIN:localhost}
    preferIpAddress: true
