spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:sonifoy-kafka:29092}
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        '[spring.deserializer.value.delegate.class]': org.springframework.kafka.support.serializer.JsonDeserializer
        '[spring.json.trusted.packages]': "*"
  cassandra:
    contact-points: ${CASSANDRA_CONTACT_POINTS:sonifoy-cassandra}
    local-datacenter: ${CASSANDRA_LOCAL_DATACENTER:datacenter1}
    keyspace-name: ${CASSANDRA_KEYSPACE:sonifoy_keyspace}
    schema-action: CREATE_IF_NOT_EXISTS
  r2dbc:
    url: r2dbc:postgresql://${DATABASE_URL_UNJ?:sonifoy-db:5432/auth_db}
    username: ${PGUSER:sonifoy_user}
    password: ${PGPASSWORD:sonifoy_password}
  data:
    redis:
      host: ${REDISHOST:sonifoy-redis}
      port: ${REDISPORT:6379}
      password: ${REDISPASSWORD:}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka/}
  instance:
    hostname: ${RAILWAY_PRIVATE_DOMAIN:localhost}
    preferIpAddress: false
